### ISSUE TITLE
not able to run goodai-ltm-benchmark 

### ISSUE THREAD

**Issue by naveen1286** [GoodAI/goodai-ltm-benchmark#62]
Hi 
I simply downloaded source code from main branch and try to run the code with following command :
python ./runner/run_benchmark.py -c ./configurations/blogpost_tests/benchmark-1k.yml -a gpt-4-1106 -m 4096
from root director of project but I get the following error :
Traceback (most recent call last):
  File "/home/ubuntu/Downloads/goodai-ltm-benchmark-2-benchmark/./runner/run_benchmark.py", line 13, in <module>
    from dataset_interfaces.factory import DatasetFactory, DATASETS
  File "/home/ubuntu/Downloads/goodai-ltm-benchmark-2-benchmark/dataset_interfaces/factory.py", line 2, in <module>
    from datasets.conficting_personal_information import ConflictingPersonalInformationDataset
ModuleNotFoundError: No module named 'datasets.conficting_personal_information'

Please help to share detail steps about how I can run this project

**Comment by dcasbol** [comment]
Hi Naveen! The issue you are having is because `main` branch contains now the version 2 of the benchmark, and `benchmark-1k.yml` is an outdated configuration file which corresponds to the first version that we ran for our first release. Try running `benchmark-v2-1k.yml`, that one should work, and let us know how it goes. Thanks for trying it out! 😁

**Comment by dcasbol** [comment]
Ah... right 😩 That is an issue we weren't able to fix. What is happening is that ChapterBreak needs to download a file from a Google drive folder, and Google won't let your machine do that automatically. To fix it, you need to manually go to that link and perform the download. In successive times, your machine will be able to do it for you.

As of running the other benchmark, I don't think that will lead to correct results, even if it lets you run it. I would suggest you to make a clean run after you fix this link issue.

To run your custom agent, you need to create a wrapper for it in `model_interfaces` and add it to the list of agents in `runner/run_benchmark.py`. And now that you mention it, we need to come up with an easier way to do this, so thanks again for trying it out, because this feedback is really important for us 😄 Check out [this readme](https://github.com/GoodAI/goodai-ltm-benchmark/tree/main/model_interfaces) (and maybe the others, too). They should help you. Feel free to reach back to us if anything else comes up!

**Comment by naveen1286** [comment]
Dear David
Thanks for your detail explanation....
I am even facing a trouble in running memgpt too .
I  was trying to run memgpt on benchmark version 1 with following command :
python3 runner/run_benchmark.py -c configurations/blogpost_tests/benchmark-10k.yml -a memgpt -m 4096

it shows following error -
  File "/home/ubuntu/goodai/venv/lib/python3.10/site-packages/memgpt/server/server.py", line 983, in delete_agent
    if self.ms.get_agent(agent_id=agent_id, user_id=user_id) is None:
  File "/home/ubuntu/goodai/venv/lib/python3.10/site-packages/memgpt/utils.py", line 520, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/goodai/venv/lib/python3.10/site-packages/memgpt/metadata.py", line 561, in get_agent
    assert agent_name is not None and user_id is not None, "Must provide either agent_id or agent_name"
AssertionError: Must provide either agent_id or agent_name



while I am passing the agent name properly. And my way works properly in case if agent is gpt-3.5

One more thing,  my final goal is to evaluate my agent based on langchain framework. but when I was trying to evaluate for langchain_ce_a with the help of following command :
python3 runner/run_benchmark.py -c configurations/blogpost_tests/benchmark-10k.yml -a langchain_ce_a -m 4096

but it throws following error -
  File "/home/ubuntu/goodai/venv/src/goodai-ltm-benchmark/runner/run_benchmark.py", line 193, in _main
    agent = get_chat_session(agent_name, max_prompt_size=max_prompt_size, run_name=config['run_name'])
  File "/home/ubuntu/goodai/venv/src/goodai-ltm-benchmark/runner/run_benchmark.py", line 59, in get_chat_session
    return LangchainAgent(
TypeError: LangchainAgent.__init__() got an unexpected keyword argument 'run_name'


Please help me out for langchain evaluation methods

**Comment by dcasbol** [comment]
There are a few things here:

**We encourage you to keep a separate environment and install the specific package versions from `requirements.txt`.** Some errors that you are experiencing might originate from it.

**Each benchmark version needs to run with the corresponding code version.** Since the system itself is evolving, we are not making them backwards compatible. In order to run the benchmark configuration from version 1, follow these steps:

1. Checkout the version 1 of the benchmark: `git checkout tags/v1-benchmark -b main`
2. Run the benchmark. We recommend you to use PyCharm, since it takes care of many details for you, like setting the working directory to the main project directory, instead of `./runner`. Also, I am not sure if the first version correctly supported MemGPT.

**The system only recognizes agents that are implemented in the main script**. Take a look at the readme to see what agents are supported, and if you want to add support to your own agent, you will need to modify the function `get_chat_session` in `runner/run_benchmark.py`.

**Comment by dcasbol** [comment]
@naveen1286 did you manage to solve those issues? In any case, I would encourage you to use the latest version of the dataset and the corresponding configuration files. Those are way more robust and useful in terms of assessing the agent's LTM capabilities. Also, we have addressed the problem with ChapterBreak as [part of our next release](https://github.com/GoodAI/goodai-ltm-benchmark/pull/69), which will come out anytime this week.

**Comment by dcasbol** [comment]
We have just released the version 3 of the benchmark, which includes a fix to the ChapterBreak issue and is now the standard to evaluate agents' LTM capabilities and should be used instead of the older ones. I will close this issue, but feel free to open a new one if new problems arise. Thanks for trying it out!
